# Generated by Django 2.1.3 on 2018-11-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comp_Name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_Name', models.CharField(max_length=255, unique=True)),
                ('Comp_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_FName', models.CharField(max_length=255)),
                ('Emp_LName', models.CharField(max_length=255)),
                ('Emp_Email', models.TextField(max_length=50)),
                ('Emp_Phone', models.IntegerField(max_length=50)),
                ('Comp_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex_app.Company')),
                ('Dept_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex_app.Department')),
            ],
        ),
    ]
